### ISSUE TITLE
Css-滚动条样式

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/js-tools#16]
::-webkit-scrollbar {
  border-radius: 5px;
}

/*定义滚动条轨道 内阴影+圆角*/
::-webkit-scrollbar-track {
  border-radius: 5px;
}

/*定义滑块 内阴影+圆角*/
::-webkit-scrollbar-thumb {
  border-radius: 5px;
  background-color: #4f5877;
}

### element隐藏的
```html
  <el-scrollbar class="mc-scroll">
        <ul>
           <li></li>
         </ul>
  </el-scrollbar>
```
```css
.mc-scroll {
  height: 100%;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  /deep/ .el-scrollbar__wrap {
    overflow-x: hidden;
  }
  ul {
    height: 40px;
    margin: 0 5px;
    border-bottom: 1px solid #5555;
    padding: 8px 0;

    li {
      display: inline-block;
      height: 100%;
      position: relative;
      line-height: 25px;

      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  }
}
```
